// <auto-generated />
using System;
using H_Katanga.educ.Areas.SuivisProfesseur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace H_Katanga.educ.Migrations.AppSuivisProfesseurMigrations
{
    [DbContext(typeof(AppSuivisProfesseur))]
    [Migration("20201022091213__migration_init_")]
    partial class _migration_init_
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("H_Katanga.educ.Areas.SuivisProfesseur.Models.CotationProfesseur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cote");

                    b.Property<string>("Description");

                    b.Property<int>("InspecteurID");

                    b.Property<string>("InspecteurID1");

                    b.Property<int>("LeconID");

                    b.Property<int>("Total");

                    b.HasKey("ID");

                    b.HasIndex("InspecteurID1");

                    b.HasIndex("LeconID")
                        .IsUnique();

                    b.ToTable("CotationProfesseurs");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SuivisProfesseur.Models.Inspecteur", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateNaissance");

                    b.Property<string>("Email");

                    b.Property<int?>("Genre");

                    b.Property<string>("Matricule")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Postnom")
                        .IsRequired();

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Inspecteurs");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SuivisProfesseur.Models.Lecon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateLecon");

                    b.Property<string>("Description");

                    b.Property<string>("IdentifiantCours");

                    b.Property<string>("Matricule");

                    b.HasKey("ID");

                    b.ToTable("Lecons");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SuivisProfesseur.Models.CotationProfesseur", b =>
                {
                    b.HasOne("H_Katanga.educ.Areas.SuivisProfesseur.Models.Inspecteur", "Inspecteur")
                        .WithMany()
                        .HasForeignKey("InspecteurID1");

                    b.HasOne("H_Katanga.educ.Areas.SuivisProfesseur.Models.Lecon", "Lecon")
                        .WithOne("CotationProfesseur")
                        .HasForeignKey("H_Katanga.educ.Areas.SuivisProfesseur.Models.CotationProfesseur", "LeconID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
