// <auto-generated />
using H_Katanga.educ.Areas.SystemeEvaluation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace H_Katanga.educ.Migrations.AppEvaluationMigrations
{
    [DbContext(typeof(AppEvaluation))]
    [Migration("20201022115746__modification_model_2")]
    partial class _modification_model_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("H_Katanga.educ.Areas.SystemeEvaluation.Models.Assertion", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Point");

                    b.Property<string>("QuestionID");

                    b.Property<string>("reponse");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Assertions");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SystemeEvaluation.Models.Examen", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeAcces");

                    b.Property<string>("Description");

                    b.Property<string>("IdentifiantClasse");

                    b.Property<string>("Serie");

                    b.Property<string>("Titre");

                    b.HasKey("ID");

                    b.ToTable("Examens");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SystemeEvaluation.Models.Question", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Enoncer");

                    b.Property<string>("ExamenID");

                    b.Property<string>("ExamenID1");

                    b.Property<string>("Solution");

                    b.HasKey("ID");

                    b.HasIndex("ExamenID");

                    b.HasIndex("ExamenID1");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SystemeEvaluation.Models.Serie", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom");

                    b.HasKey("ID");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SystemeEvaluation.Models.Assertion", b =>
                {
                    b.HasOne("H_Katanga.educ.Areas.SystemeEvaluation.Models.Question", "Question")
                        .WithMany("Assertions")
                        .HasForeignKey("QuestionID");
                });

            modelBuilder.Entity("H_Katanga.educ.Areas.SystemeEvaluation.Models.Question", b =>
                {
                    b.HasOne("H_Katanga.educ.Areas.SystemeEvaluation.Models.Examen")
                        .WithMany("Qtns")
                        .HasForeignKey("ExamenID");

                    b.HasOne("H_Katanga.educ.Areas.SystemeEvaluation.Models.Examen")
                        .WithMany("Questions")
                        .HasForeignKey("ExamenID1");
                });
#pragma warning restore 612, 618
        }
    }
}
