// <auto-generated />
using System;
using H_Katanga.educ.Areas.PerformanceEleve.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace H_Katanga.educ.Migrations.AppPerformanceEleveMigrations
{
    [DbContext(typeof(AppPerformanceEleve))]
    [Migration("20201022114659__modification_model_")]
    partial class _modification_model_
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("H_Katanga.educ.Areas.PerformanceEleve.Models.Epreuve", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cote");

                    b.Property<DateTime>("DateEpreuve");

                    b.Property<string>("Description");

                    b.Property<string>("IdentifiantClasse");

                    b.Property<string>("IdentifiantCours");

                    b.Property<string>("MAtriculeEleve");

                    b.Property<int>("Total");

                    b.HasKey("ID");

                    b.ToTable("Epreuves");
                });
#pragma warning restore 612, 618
        }
    }
}
